import type React from "react"
import type { Metadata } from "next"
import { Inter, Fira_Code } from "next/font/google"
// import { ThemeProvider } from "@/components/ui/theme-provider"
import { ThemeProvider } from "next-themes"
import "./globals.css"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const firaCode = Fira_Code({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "PeerPrep - Code Together. Prep Together",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="font-sans">
      <body className={`${inter.variable} ${firaCode.variable} antialiased`}>
        <Analytics />
        <ThemeProvider attribute="class" defaultTheme="system" storageKey="competition-theme">
          {children}
        </ThemeProvider>
        <SpeedInsights />
      </body>
    </html>
  )
}
