import type React from "react"
import type { Metadata } from "next"
import { Inter, Fira_Code } from "next/font/google"
import { ThemeProvider } from "@/components/ui/theme-provider"
import "./globals.css"

const inter = Inter({
  variable: "--font-geist-sans", // Keep your variable name if needed
  subsets: ["latin"],
})

const firaCode = Fira_Code({
  variable: "--font-geist-mono", // Matching your old variable name
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${firaCode.variable} antialiased`}>
        <ThemeProvider defaultTheme="system" storageKey="competition-theme">
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
